services:
  inventory_web:
    build:
      context: .
      target: runtime
    # Usa Uvicorn via Gunicorn para produção
    command: /start.sh
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env.prod
    environment:
      - DEBUG=0
      - DJANGO_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=redis://inventory_redis:6379/0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    depends_on:
      inventory_db:
        condition: service_healthy
      inventory_redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory_worker:
    build:
      context: .
      target: runtime
    command: celery -A app worker -l info -E --concurrency=2
    env_file:
      - .env.prod
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    depends_on:
      inventory_db:
        condition: service_healthy
      inventory_redis:
        condition: service_healthy

  inventory_flower:
    build:
      context: .
      target: runtime
    command: celery -A app flower --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env.prod
    depends_on:
      inventory_redis:
        condition: service_healthy

  inventory_db:
    image: postgres:17.7-alpine3.23
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod

  inventory_redis:
    image: redis:8.2.3-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data_prod:/data

  inventory_nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./site:/inventory-management-django-system/site
    ports:
      - "80:80"
    depends_on:
      - inventory_web

volumes:
  postgres_data_prod:
  redis_data_prod:
  static_volume:
  media_volume: